//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PressWatchEntities : DbContext
    {
        public PressWatchEntities()
            : base("name=PressWatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public  DbSet<Gender> Genders { get; set; }
        public  DbSet<Movy> Movies { get; set; }
        public  DbSet<Role> Roles { get; set; }
        public  DbSet<User> Users { get; set; }
    }
}
