//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movy
    {
        public int id { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        [Range(0, 10)]
        public Nullable<int> Rating { get; set; }


        [Range(1000, 3000)]
        public Nullable<int> Release_Year { get; set; }

        public string Movie_Img { get; set; }

        [StringLength(50)]
        public string Description { get; set; }

        public string Movie_Trailer { get; set; }
    }
}
